#!/bin/bash
# 颜色
CYAN="\033[1;36m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
RESET="\033[0m"

# 系统信息
HOSTNAME=$(hostname)
KERNEL=$(uname -r)
UPTIME=$(uptime -p | sed 's/up //')
LOAD=$(cut -d " " -f1-3 /proc/loadavg)
MEM=$(free -h | awk '/Mem:/ {print $3 "/" $2}')
DISK=$(df -h / | awk 'NR==2 {print $3 "/" $2 " (" $5 ")"}')
IPv4=$(hostname -I | awk '{print $1}')
IPv6=$(hostname -I | tr ' ' '\n' | grep ':' | grep -v '^fe80' | sed 's/^/[/' | sed 's/$/]/' | tr '\n' ' ')

echo -e "${GREEN}Hostname:${RESET}      $HOSTNAME"
echo -e "${GREEN}Kernel:${RESET}        $KERNEL"
echo -e "${GREEN}Uptime:${RESET}        $UPTIME"
echo -e "${GREEN}Load:${RESET}          $LOAD"
echo -e "${GREEN}Memory:${RESET}        $MEM"
echo -e "${GREEN}Disk:${RESET}          $DISK"
echo -e "${GREEN}IPv4:${RESET}          $IPv4"
echo -e "${GREEN}IPv6:${RESET}          $IPv6"
echo ""
echo -e "${YELLOW}-------------------------------------------------------------------------------------------${RESET}"
## echo "shadowsocks-rust: cat /etc/shadowsocks-rust/config.json | aes-128-gcm 10443 + 44433 + chacha20 10203"
